import { useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowRight, Search } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useNavigation } from '@/lib/navigation/useNavigation';
import { cn } from '@/lib/utils';

export function CommandPalette({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [query, setQuery] = useState('');
  const [selectedIndex, setSelectedIndex] = useState(0);
  const navigate = useNavigate();
  const items = useNavigation();
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return q ? items.filter((item) => item.labelKey.toLowerCase().includes(q) || item.path.toLowerCase().includes(q)) : items; }, [items, query]);
  useEffect(() => { queueMicrotask(() => setSelectedIndex(0)); }, [query]);
  useEffect(() => { if (!open) { queueMicrotask(() => setQuery('')); return; } const handleKey = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); if (event.key === 'ArrowDown') { event.preventDefault(); setSelectedIndex((i) => Math.min(i + 1, Math.max(filtered.length - 1, 0))); } if (event.key === 'ArrowUp') { event.preventDefault(); setSelectedIndex((i) => Math.max(i - 1, 0)); } if (event.key === 'Enter' && filtered[selectedIndex]) { navigate(filtered[selectedIndex].path); onClose(); } }; window.addEventListener('keydown', handleKey); return () => window.removeEventListener('keydown', handleKey); }, [filtered, navigate, onClose, open, selectedIndex]);
  return <AnimatePresence>{open && <><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm" onClick={onClose} /><motion.div initial={{ opacity: 0, scale: 0.95, y: -20 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: 0.95, y: -20 }} transition={{ type: 'spring', stiffness: 300, damping: 25 }} className="fixed left-1/2 top-[15%] z-50 w-[calc(100%-2rem)] max-w-xl -translate-x-1/2" role="dialog" aria-modal="true" aria-label="Быстрый поиск"><div className="overflow-hidden rounded-2xl border border-border bg-card shadow-2xl"><div className="flex items-center gap-3 border-b border-border px-4 py-3"><Search className="h-5 w-5 shrink-0 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Поиск страниц, действий..." autoFocus className="flex-1 bg-transparent text-foreground outline-none placeholder:text-muted-foreground" aria-label="Поисковый запрос" /><kbd className="hidden rounded border border-border bg-muted px-1.5 py-0.5 font-mono text-[10px] text-muted-foreground md:inline-flex">ESC</kbd></div><div className="max-h-96 overflow-y-auto p-2">{filtered.length === 0 ? <div className="px-4 py-8 text-center text-muted-foreground">Ничего не найдено</div> : filtered.map((item, index) => { const Icon = item.icon; return <button key={item.id} type="button" onClick={() => { navigate(item.path); onClose(); }} onMouseEnter={() => setSelectedIndex(index)} className={cn('flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left transition-colors', index === selectedIndex ? 'bg-accent text-accent-foreground' : 'text-foreground hover:bg-muted')}><Icon className="h-4 w-4 shrink-0" /><span className="flex-1 text-sm font-medium">{item.labelKey}</span>{index === selectedIndex && <ArrowRight className="h-4 w-4 shrink-0" />}</button>; })}</div><div className="flex items-center justify-between border-t border-border px-4 py-2 text-xs text-muted-foreground"><div className="flex items-center gap-3"><span>↑↓ навигация</span><span>↵ выбрать</span></div><span>{filtered.length} результатов</span></div></div></motion.div></>}</AnimatePresence>;
}
