import {
  BookOpen,
  Calendar,
  Crown,
  FileText,
  Heart,
  Home,
  Lightbulb,
  Link2,
  Settings,
  ShieldCheck,
  Sparkles,
  Users,
  Wallet,
} from 'lucide-react';

import type { NavigationItem } from '@/lib/navigation/types';

export const navigationConfig = [
  {
    id: 'home',
    path: '/',
    labelKey: 'nav.home',
    icon: Home,
    group: 'main',
    surface: 'participant',
    minRole: 'newcomer',
    shortcut: '0',
    binding: {
      owner: 'main-entry',
      componentPath: 'src/App.tsx',
    },
    preserveExistingRoute: true,
  },
  {
    id: 'my-path',
    path: '/my-path',
    labelKey: 'nav.myPath',
    icon: Sparkles,
    group: 'main',
    surface: 'participant',
    minRole: 'newcomer',
    shortcut: '1',
    binding: {
      owner: 'app-shell',
      componentPath: 'src/pages/MyPath.tsx',
      appProp: 'myPathPage',
    },
    preserveExistingRoute: true,
  },
  {
    id: 'community',
    path: '/community',
    labelKey: 'nav.community',
    icon: Users,
    group: 'community',
    surface: 'participant',
    minRole: 'member',
    shortcut: '2',
    binding: {
      owner: 'app-shell',
      componentPath: 'src/pages/CommunityFeed.tsx',
      appProp: 'communityFeedPage',
    },
    preserveExistingRoute: true,
  },
  {
    id: 'learning',
    path: '/learning',
    labelKey: 'nav.learning',
    icon: BookOpen,
    group: 'community',
    surface: 'participant',
    minRole: 'member',
    shortcut: '3',
    binding: {
      owner: 'app-shell',
      componentPath: 'src/pages/LearningPage.tsx',
      appProp: 'learningPage',
    },
    preserveExistingRoute: true,
  },
  {
    id: 'meetings',
    path: '/meetings',
    labelKey: 'nav.meetings',
    icon: Calendar,
    group: 'community',
    surface: 'participant',
    minRole: 'member',
    shortcut: '4',
    badge: { type: 'dot', source: 'notifications' },
    binding: {
      owner: 'app-shell',
      componentPath: 'src/pages/MeetingsPage.tsx',
      appProp: 'meetingsPage',
    },
    preserveExistingRoute: true,
  },
  {
    id: 'connections',
    path: '/connections',
    labelKey: 'nav.connections',
    icon: Link2,
    group: 'community',
    surface: 'participant',
    minRole: 'member',
    shortcut: '5',
    binding: {
      owner: 'app-shell',
      componentPath: 'src/pages/MyConnections.tsx',
      appProp: 'connectionsPage',
    },
    preserveExistingRoute: true,
  },
  {
    id: 'insights',
    path: '/insights',
    labelKey: 'nav.insights',
    icon: Lightbulb,
    group: 'community',
    surface: 'participant',
    minRole: 'member',
    shortcut: '6',
    binding: {
      owner: 'app-shell',
      componentPath: 'src/pages/InsightsPage.tsx',
      appProp: 'insightsPage',
    },
    preserveExistingRoute: true,
  },
  {
    id: 'contribution',
    path: '/contribution',
    labelKey: 'nav.contribution',
    icon: Heart,
    group: 'community',
    surface: 'participant',
    minRole: 'member',
    shortcut: '7',
    binding: {
      owner: 'app-shell',
      componentPath: 'src/pages/ContributionPage.tsx',
      appProp: 'contributionPage',
    },
    preserveExistingRoute: true,
  },
  {
    id: 'community-about',
    path: '/community/about',
    labelKey: 'nav.communityAbout',
    icon: FileText,
    group: 'public',
    surface: 'public',
    minRole: 'guest',
    binding: {
      owner: 'standalone',
      componentPath: 'src/CommunityLanding.tsx',
    },
    preserveExistingRoute: true,
  },
  {
    id: 'leader-console',
    path: '/leader',
    labelKey: 'nav.leaderConsole',
    icon: Crown,
    group: 'leadership',
    surface: 'leader',
    minRole: 'leader',
    shortcut: '8',
    binding: {
      owner: 'leader-shell',
      componentPath: 'src/LeaderConsoleMain.tsx',
      appProp: 'leaderMode',
      leaderTab: 'main',
    },
    preserveExistingRoute: true,
  },
  {
    id: 'leader-entry',
    path: '/leader/entry',
    labelKey: 'nav.leaderEntry',
    icon: ShieldCheck,
    group: 'leadership',
    surface: 'leader',
    minRole: 'leader',
    badge: { type: 'count', source: 'applications' },
    binding: {
      owner: 'leader-shell',
      componentPath: 'src/LeaderConsoleEntry.tsx',
      appProp: 'leaderMode',
      leaderTab: 'entry',
    },
    preserveExistingRoute: true,
  },
  {
    id: 'leader-requests',
    path: '/leader/requests',
    labelKey: 'nav.leaderRequests',
    icon: FileText,
    group: 'leadership',
    surface: 'leader',
    minRole: 'leader',
    binding: {
      owner: 'leader-shell',
      componentPath: 'src/LeaderConsoleRequests.tsx',
      appProp: 'leaderMode',
      leaderTab: 'requests',
    },
    preserveExistingRoute: true,
  },
  {
    id: 'leader-connections',
    path: '/leader/connections',
    labelKey: 'nav.leaderConnections',
    icon: Link2,
    group: 'leadership',
    surface: 'leader',
    minRole: 'leader',
    binding: {
      owner: 'leader-shell',
      componentPath: 'src/LeaderConsoleConnections.tsx',
      appProp: 'leaderMode',
      leaderTab: 'connections',
    },
    preserveExistingRoute: true,
  },
  {
    id: 'leader-contribution',
    path: '/leader/contribution',
    labelKey: 'nav.leaderContribution',
    icon: Heart,
    group: 'leadership',
    surface: 'leader',
    minRole: 'leader',
    binding: {
      owner: 'leader-shell',
      componentPath: 'src/LeaderConsoleContribution.tsx',
      appProp: 'leaderMode',
      leaderTab: 'contribution',
    },
    preserveExistingRoute: true,
  },
  {
    id: 'leader-monetization',
    path: '/leader/monetization',
    labelKey: 'nav.leaderMonetization',
    icon: Wallet,
    group: 'leadership',
    surface: 'leader',
    minRole: 'leader',
    binding: {
      owner: 'leader-shell',
      componentPath: 'src/LeaderConsoleMonetization.tsx',
      appProp: 'leaderMode',
      leaderTab: 'monetization',
    },
    preserveExistingRoute: true,
  },
  {
    id: 'leader-settings',
    path: '/leader/settings',
    labelKey: 'nav.leaderSettings',
    icon: Settings,
    group: 'leadership',
    surface: 'leader',
    minRole: 'leader',
    binding: {
      owner: 'leader-shell',
      componentPath: 'src/LeaderConsoleSettings.tsx',
      appProp: 'leaderMode',
      leaderTab: 'settings',
    },
    preserveExistingRoute: true,
  },
] as const satisfies readonly NavigationItem[];

export type NavigationItemId = (typeof navigationConfig)[number]['id'];
